// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUG8zIb6J0rvtmOUS6sbgYlKpErIBJko',
    appId: '1:706128472658:android:2cbed47eb8ec53ff750d8b',
    messagingSenderId: '706128472658',
    projectId: 'flutter-auth-app-ef416',
    storageBucket: 'flutter-auth-app-ef416.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoS30W-plcDiXgbu5NLQ5KY2Fd_WVibYw',
    appId: '1:706128472658:ios:0513d77c9ea204e0750d8b',
    messagingSenderId: '706128472658',
    projectId: 'flutter-auth-app-ef416',
    storageBucket: 'flutter-auth-app-ef416.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4X-Mzt7fZHhwBQ005qexFsHTkkdDVsYU',
    appId: '1:706128472658:web:3957b200d6cbd6f2750d8b',
    messagingSenderId: '706128472658',
    projectId: 'flutter-auth-app-ef416',
    authDomain: 'flutter-auth-app-ef416.firebaseapp.com',
    storageBucket: 'flutter-auth-app-ef416.firebasestorage.app',
    measurementId: 'G-CGC3KQN7L0',
  );
}
